// ============================================================
// Bougeotte — Base de données des organismes français
// ============================================================

export const CATEGORIES = [
  { id: 'banque', label: 'Banques', icon: '🏦', color: '#6366f1' },
  { id: 'assurance', label: 'Assurances', icon: '🛡️', color: '#8b5cf6' },
  { id: 'telecom', label: 'Télécom & Internet', icon: '📡', color: '#06b6d4' },
  { id: 'energie', label: 'Énergie', icon: '⚡', color: '#f59e0b' },
  { id: 'sante', label: 'Santé & Mutuelle', icon: '🏥', color: '#10b981' },
  { id: 'administration', label: 'Administration', icon: '🏛️', color: '#ef4444' },
  { id: 'emploi', label: 'Emploi & Formation', icon: '💼', color: '#ec4899' },
  { id: 'transport', label: 'Transport', icon: '🚗', color: '#14b8a6' },
  { id: 'logement', label: 'Logement', icon: '🏠', color: '#f97316' },
  { id: 'divers', label: 'Autres services', icon: '📦', color: '#64748b' },
];

export const ORGANISMES = [
  // ── BANQUES ──────────────────────────────────────────────
  {
    id: 'bnp',
    nom: 'BNP Paribas',
    categorie: 'banque',
    type: 'courrier',
    adresse: 'BNP Paribas — Service Clients\n16 boulevard des Italiens\n75009 Paris',
    email: null,
    url: 'https://mabanque.bnpparibas',
    note: 'Changement possible via l\'espace client en ligne ou en agence.',
    populaire: true,
  },
  {
    id: 'sg',
    nom: 'Société Générale',
    categorie: 'banque',
    type: 'courrier',
    adresse: 'Société Générale — Service Clients\n29 boulevard Haussmann\n75009 Paris',
    email: null,
    url: 'https://particuliers.societegenerale.fr',
    note: 'Contactez votre agence directement ou via l\'application.',
    populaire: true,
  },
  {
    id: 'ca',
    nom: 'Crédit Agricole',
    categorie: 'banque',
    type: 'courrier',
    adresse: 'Crédit Agricole — Votre agence locale',
    email: null,
    url: 'https://www.credit-agricole.fr',
    note: 'Adressez le courrier à votre agence locale.',
    populaire: true,
  },
  {
    id: 'lcl',
    nom: 'LCL',
    categorie: 'banque',
    type: 'courrier',
    adresse: 'LCL — Service Clients\n20 avenue de Paris\n94811 Villejuif Cedex',
    email: null,
    url: 'https://www.lcl.fr',
    note: 'Modification possible en agence ou via l\'espace client.',
    populaire: false,
  },
  {
    id: 'bp',
    nom: 'Banque Populaire',
    categorie: 'banque',
    type: 'courrier',
    adresse: 'Banque Populaire — Votre agence locale',
    email: null,
    url: 'https://www.banquepopulaire.fr',
    note: 'Contactez votre agence de rattachement.',
    populaire: false,
  },
  {
    id: 'ce',
    nom: 'Caisse d\'Épargne',
    categorie: 'banque',
    type: 'courrier',
    adresse: 'Caisse d\'Épargne — Votre agence locale',
    email: null,
    url: 'https://www.caisse-epargne.fr',
    note: 'Modification en agence ou via l\'espace sécurisé.',
    populaire: false,
  },
  {
    id: 'boursorama',
    nom: 'Boursorama Banque',
    categorie: 'banque',
    type: 'email',
    adresse: null,
    email: 'service.client@boursorama.fr',
    url: 'https://www.boursorama-banque.com',
    note: 'Changement d\'adresse directement dans l\'app ou par email.',
    populaire: true,
  },
  {
    id: 'fortuneo',
    nom: 'Fortuneo',
    categorie: 'banque',
    type: 'email',
    adresse: null,
    email: 'service.clients@fortuneo.fr',
    url: 'https://www.fortuneo.fr',
    note: 'Modifiable dans l\'espace client ou par email.',
    populaire: false,
  },

  // ── ASSURANCES ───────────────────────────────────────────
  {
    id: 'axa',
    nom: 'AXA',
    categorie: 'assurance',
    type: 'courrier',
    adresse: 'AXA France — Service Clients\n313 Terrasses de l\'Arche\n92727 Nanterre Cedex',
    email: null,
    url: 'https://www.axa.fr',
    note: 'Important : mettez à jour auto + habitation + santé.',
    populaire: true,
  },
  {
    id: 'allianz',
    nom: 'Allianz',
    categorie: 'assurance',
    type: 'courrier',
    adresse: 'Allianz France — Service Clients\n1 cours Michelet\n92076 Paris La Défense Cedex',
    email: null,
    url: 'https://www.allianz.fr',
    note: 'Pensez à déclarer votre nouveau logement pour l\'assurance habitation.',
    populaire: true,
  },
  {
    id: 'maif',
    nom: 'MAIF',
    categorie: 'assurance',
    type: 'email',
    adresse: 'MAIF\n200 avenue Salvador Allende\n79038 Niort Cedex 9',
    email: 'sociétaires@maif.fr',
    url: 'https://www.maif.fr',
    note: 'Modification possible en ligne dans l\'espace sociétaire.',
    populaire: true,
  },
  {
    id: 'macif',
    nom: 'MACIF',
    categorie: 'assurance',
    type: 'courrier',
    adresse: 'MACIF — Service Sociétaires\n2-4 rue de Pied de Fond\n79037 Niort Cedex 9',
    email: null,
    url: 'https://www.macif.fr',
    note: 'Déclarez votre déménagement au moins 15 jours avant.',
    populaire: false,
  },
  {
    id: 'groupama',
    nom: 'Groupama',
    categorie: 'assurance',
    type: 'courrier',
    adresse: 'Groupama — Votre agence locale',
    email: null,
    url: 'https://www.groupama.fr',
    note: 'Contactez votre caisse régionale Groupama.',
    populaire: false,
  },
  {
    id: 'mma',
    nom: 'MMA',
    categorie: 'assurance',
    type: 'courrier',
    adresse: 'MMA — Service Clients\n14 boulevard Marie et Alexandre Oyon\n72030 Le Mans Cedex 9',
    email: null,
    url: 'https://www.mma.fr',
    note: 'Envoyez un courrier recommandé pour garder une preuve.',
    populaire: false,
  },
  {
    id: 'maaf',
    nom: 'MAAF',
    categorie: 'assurance',
    type: 'courrier',
    adresse: 'MAAF Assurances\nChauray — 79036 Niort Cedex 9',
    email: null,
    url: 'https://www.maaf.fr',
    note: 'Modification en ligne ou par courrier.',
    populaire: false,
  },

  // ── TELECOM & INTERNET ──────────────────────────────────
  {
    id: 'orange',
    nom: 'Orange',
    categorie: 'telecom',
    type: 'email',
    adresse: 'Orange — Service Clients\n33734 Bordeaux Cedex 9',
    email: null,
    url: 'https://www.orange.fr/portail',
    note: 'Déménagement de votre box : planifiez le transfert de ligne dans votre espace client.',
    populaire: true,
  },
  {
    id: 'sfr',
    nom: 'SFR',
    categorie: 'telecom',
    type: 'email',
    adresse: null,
    email: null,
    url: 'https://www.sfr.fr',
    note: 'Demandez le déménagement de votre box via l\'espace client SFR.',
    populaire: true,
  },
  {
    id: 'free',
    nom: 'Free',
    categorie: 'telecom',
    type: 'email',
    adresse: null,
    email: null,
    url: 'https://www.free.fr',
    note: 'Déménagement Freebox : rendez-vous sur votre espace abonné.',
    populaire: true,
  },
  {
    id: 'bouygues',
    nom: 'Bouygues Telecom',
    categorie: 'telecom',
    type: 'email',
    adresse: null,
    email: null,
    url: 'https://www.bouyguestelecom.fr',
    note: 'Transférez votre ligne via l\'espace client ou appelez le 1064.',
    populaire: true,
  },

  // ── ÉNERGIE ──────────────────────────────────────────────
  {
    id: 'edf',
    nom: 'EDF',
    categorie: 'energie',
    type: 'email',
    adresse: null,
    email: null,
    url: 'https://www.edf.fr',
    note: 'Résiliez l\'ancien contrat et ouvrez-en un nouveau. Planifiez 15 jours avant.',
    populaire: true,
  },
  {
    id: 'engie',
    nom: 'Engie (ex-GDF Suez)',
    categorie: 'energie',
    type: 'email',
    adresse: null,
    email: null,
    url: 'https://www.engie.fr',
    note: 'Résiliation ancien logement + souscription nouveau contrat.',
    populaire: true,
  },
  {
    id: 'totalenergies',
    nom: 'TotalEnergies',
    categorie: 'energie',
    type: 'email',
    adresse: null,
    email: null,
    url: 'https://www.totalenergies.fr',
    note: 'Déménagement possible en ligne dans l\'espace client.',
    populaire: false,
  },
  {
    id: 'veolia',
    nom: 'Veolia Eau',
    categorie: 'energie',
    type: 'courrier',
    adresse: 'Veolia Eau — Service Clients\nVotre agence locale',
    email: null,
    url: 'https://www.service-client.veolia.fr',
    note: 'Résiliation de l\'abonnement eau de l\'ancien logement.',
    populaire: false,
  },

  // ── SANTÉ & MUTUELLE ─────────────────────────────────────
  {
    id: 'cpam',
    nom: 'CPAM (Sécurité Sociale)',
    categorie: 'sante',
    type: 'email',
    adresse: null,
    email: null,
    url: 'https://www.ameli.fr',
    note: 'Changement d\'adresse en ligne sur ameli.fr — rubrique "Mon compte".',
    populaire: true,
  },
  {
    id: 'harmonie',
    nom: 'Harmonie Mutuelle',
    categorie: 'sante',
    type: 'courrier',
    adresse: 'Harmonie Mutuelle — Service Adhérents\n143 rue Blomet\n75015 Paris',
    email: null,
    url: 'https://www.harmonie-mutuelle.fr',
    note: 'Modification en ligne ou par courrier.',
    populaire: false,
  },
  {
    id: 'mgen',
    nom: 'MGEN',
    categorie: 'sante',
    type: 'courrier',
    adresse: 'MGEN — Centre de gestion\n3 square Max Hymans\n75748 Paris Cedex 15',
    email: null,
    url: 'https://www.mgen.fr',
    note: 'Importante : mise à jour pour le remboursement des soins.',
    populaire: false,
  },
  {
    id: 'medecin',
    nom: 'Médecin traitant',
    categorie: 'sante',
    type: 'courrier',
    adresse: 'Votre médecin traitant',
    email: null,
    url: null,
    note: 'Si vous changez de ville, pensez à déclarer un nouveau médecin traitant sur ameli.fr.',
    populaire: true,
  },

  // ── ADMINISTRATION ────────────────────────────────────────
  {
    id: 'impots',
    nom: 'Centre des Impôts',
    categorie: 'administration',
    type: 'email',
    adresse: null,
    email: null,
    url: 'https://www.impots.gouv.fr',
    note: 'Changement d\'adresse en ligne sur impots.gouv.fr. Obligatoire pour la taxe d\'habitation.',
    populaire: true,
  },
  {
    id: 'caf',
    nom: 'CAF (Allocations Familiales)',
    categorie: 'administration',
    type: 'email',
    adresse: null,
    email: null,
    url: 'https://www.caf.fr',
    note: 'Déclarez votre déménagement sur caf.fr — impact sur les aides au logement (APL/ALS).',
    populaire: true,
  },
  {
    id: 'prefecture',
    nom: 'Préfecture (Carte grise)',
    categorie: 'administration',
    type: 'email',
    adresse: null,
    email: null,
    url: 'https://www.ants.gouv.fr',
    note: 'Obligatoire : mise à jour de la carte grise sous 1 mois (gratuit sur ANTS).',
    populaire: true,
  },
  {
    id: 'elections',
    nom: 'Mairie (Listes électorales)',
    categorie: 'administration',
    type: 'courrier',
    adresse: 'Mairie de votre nouvelle commune\nService Élections',
    email: null,
    url: 'https://www.service-public.fr/particuliers/vosdroits/R16396',
    note: 'Inscrivez-vous sur les listes électorales de votre nouvelle commune.',
    populaire: true,
  },
  {
    id: 'laposte',
    nom: 'La Poste (Réexpédition)',
    categorie: 'administration',
    type: 'email',
    adresse: null,
    email: null,
    url: 'https://www.laposte.fr/demenagement',
    note: 'Service payant (~30-60€ selon durée). Réexpédie votre courrier pendant 6 ou 12 mois.',
    populaire: true,
  },

  // ── EMPLOI & FORMATION ───────────────────────────────────
  {
    id: 'francetravail',
    nom: 'France Travail (ex-Pôle Emploi)',
    categorie: 'emploi',
    type: 'email',
    adresse: null,
    email: null,
    url: 'https://www.francetravail.fr',
    note: 'Mise à jour obligatoire si vous êtes demandeur d\'emploi.',
    populaire: true,
  },
  {
    id: 'employeur',
    nom: 'Employeur',
    categorie: 'emploi',
    type: 'email',
    adresse: 'Service Ressources Humaines\nVotre entreprise',
    email: null,
    url: null,
    note: 'Prévenez les RH pour la mise à jour du bulletin de paie et du prélèvement à la source.',
    populaire: true,
  },
  {
    id: 'retraite',
    nom: 'Caisse de retraite (Agirc-Arrco)',
    categorie: 'emploi',
    type: 'courrier',
    adresse: 'Agirc-Arrco — Service Retraite\n16-18 rue Jules César\n75592 Paris Cedex 12',
    email: null,
    url: 'https://www.agirc-arrco.fr',
    note: 'Pour les retraités : mise à jour de l\'adresse de versement.',
    populaire: false,
  },

  // ── TRANSPORT ────────────────────────────────────────────
  {
    id: 'navigo',
    nom: 'Île-de-France Mobilités (Navigo)',
    categorie: 'transport',
    type: 'email',
    adresse: null,
    email: null,
    url: 'https://www.iledefrance-mobilites.fr',
    note: 'Mise à jour pour le pass Navigo — impact sur les zones tarifaires.',
    populaire: false,
  },
  {
    id: 'sncf',
    nom: 'SNCF (Carte de réduction)',
    categorie: 'transport',
    type: 'email',
    adresse: null,
    email: null,
    url: 'https://www.sncf-connect.com',
    note: 'Modifiable dans l\'espace client SNCF Connect.',
    populaire: false,
  },
  {
    id: 'stationnement',
    nom: 'Service stationnement (Mairie)',
    categorie: 'transport',
    type: 'courrier',
    adresse: 'Mairie de votre nouvelle commune\nService Stationnement',
    email: null,
    url: null,
    note: 'Demandez une carte de stationnement résidentiel si nécessaire.',
    populaire: false,
  },

  // ── LOGEMENT ─────────────────────────────────────────────
  {
    id: 'proprietaire',
    nom: 'Propriétaire / Agence immobilière',
    categorie: 'logement',
    type: 'courrier',
    adresse: 'Votre propriétaire ou agence immobilière',
    email: null,
    url: null,
    note: 'Envoyez votre préavis de départ en recommandé avec AR (1 ou 3 mois selon zone).',
    populaire: true,
  },
  {
    id: 'syndic',
    nom: 'Syndic de copropriété',
    categorie: 'logement',
    type: 'courrier',
    adresse: 'Votre syndic de copropriété',
    email: null,
    url: null,
    note: 'Si vous êtes propriétaire : informez le syndic de votre nouvelle adresse.',
    populaire: false,
  },
  {
    id: 'assurance_hab',
    nom: 'Assurance habitation (nouveau)',
    categorie: 'logement',
    type: 'courrier',
    adresse: 'Votre compagnie d\'assurance',
    email: null,
    url: null,
    note: 'Obligatoire : souscrivez une assurance pour le nouveau logement avant l\'emménagement.',
    populaire: true,
  },

  // ── DIVERS ───────────────────────────────────────────────
  {
    id: 'ecole',
    nom: 'École / Université',
    categorie: 'divers',
    type: 'courrier',
    adresse: 'L\'établissement scolaire de vos enfants',
    email: null,
    url: null,
    note: 'Prévenez l\'école actuelle et inscrivez les enfants dans la nouvelle commune.',
    populaire: true,
  },
  {
    id: 'creche',
    nom: 'Crèche / Garderie',
    categorie: 'divers',
    type: 'courrier',
    adresse: 'Votre crèche ou garderie',
    email: null,
    url: null,
    note: 'Prévenez pour la résiliation et cherchez une place dans la nouvelle ville.',
    populaire: false,
  },
  {
    id: 'salle_sport',
    nom: 'Salle de sport',
    categorie: 'divers',
    type: 'courrier',
    adresse: 'Votre salle de sport',
    email: null,
    url: null,
    note: 'Le déménagement est un motif de résiliation anticipée (loi Chatel).',
    populaire: false,
  },
  {
    id: 'amazon',
    nom: 'Amazon',
    categorie: 'divers',
    type: 'email',
    adresse: null,
    email: null,
    url: 'https://www.amazon.fr',
    note: 'Mettez à jour l\'adresse de livraison par défaut.',
    populaire: true,
  },
  {
    id: 'netflix',
    nom: 'Abonnements streaming (Netflix, etc.)',
    categorie: 'divers',
    type: 'email',
    adresse: null,
    email: null,
    url: null,
    note: 'Mettez à jour l\'adresse de facturation dans vos comptes.',
    populaire: false,
  },
  {
    id: 'veterinaire',
    nom: 'Vétérinaire',
    categorie: 'divers',
    type: 'courrier',
    adresse: 'Votre cabinet vétérinaire',
    email: null,
    url: null,
    note: 'Transférez le dossier si vous changez de vétérinaire.',
    populaire: false,
  },
];

// Helper functions
export function getOrganismesByCategorie(categorieId) {
  return ORGANISMES.filter(o => o.categorie === categorieId);
}

export function getPopulaires() {
  return ORGANISMES.filter(o => o.populaire);
}

export function getOrganismeById(id) {
  return ORGANISMES.find(o => o.id === id);
}

export function getCategorieById(id) {
  return CATEGORIES.find(c => c.id === id);
}
